### ISSUE TITLE
Retrained the models and not able to replicate the paper's results

### ISSUE THREAD

**Issue by sidsvash26** [SI3P/supWSD#12]
I was finally able to retrain the models from scratch, but I'm not able to replicate the numbers in the table reported in the paper. I used the following configuration file to train on semcor:
```
<?xml version="1.0" encoding="UTF-8"?>
<supWSD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="supconfig.xsd">
	<working_directory>trained_models</working_directory>
	<parser mns="">semeval13</parser>
	<preprocessing>
		<!--<pipeline model=""></pipeline>-->	
		<splitter model="">stanford</splitter>
		<tokenizer model="">stanford</tokenizer>
		<tagger model="">stanford</tagger>
		<lemmatizer model="">stanford</lemmatizer>
		<dependency_parser model="">stanford</dependency_parser>
	</preprocessing>
	<extraction>
		<features>
			<pos_tags cutoff="0">true</pos_tags>
			<local_collocations cutoff="0">true</local_collocations>
			<surrounding_words cutoff="0" window="1">true</surrounding_words>
			<word_embeddings strategy="EXP" window="5"
				vectors="/Users/sidvash/Dropbox/research/wsd/supWSD/embeddings_skip_wackyen_400d.bin"
				vocab="/Users/sidvash/Dropbox/research/wsd/supWSD/wackyEN.vocab.txt" cache="1">false</word_embeddings>
			<syntactic_relations>true</syntactic_relations>
		</features>
	</extraction>
	<classifier>libsvm</classifier>
	<writer>all</writer>
	<sense_inventory
		dict="/Users/sidvash/Dropbox/research/wsd/supWSD/wn3_dict/">wordnet</sense_inventory>
</supWSD>
```
When I test the trained model on semeval13 and semeval15 from Raganato's Evaluation datasets, I get the following numbers:
F1 (semeval2013): 0.590
F1 (semeval2015): 0.639

The numbers reported in the paper with only semcor training (without embeddings) are as follows:
F1 (semeval2013): 0.658
F1 (semeval2015): 0.70

Am I missing something in the configuration file? I couldn't find the exact configurations in the paper that were used to report the numbers. So I used the above ones. Please let me know what am I missing here.

**Comment by raganato** [comment]
change the window of the surrounding_words feature with -1, set to false the syntactic_relations feature, and use liblinear as classifier

**Comment by sidsvash26** [comment]
Thanks for your response. I'll try that.
