### ISSUE TITLE
Java .bin Offline for supwsd?

### ISSUE THREAD

**Issue by rodriguesfas** [SI3P/supWSD#14]
Hello, would you have a bin file to run supwsd offline via command, would you ever set up a project in eclipse? Because the TollKit documentation was not a clear myth for me, I could not make it work.

would be something like: java -jar supwsd.bin < sentence >

then it would already bring me a JSON with the result of the sentence analyzed.

**Comment by SI3P** [comment]
I will publish a light version of supwsd to directly disambiguate sentences using existing models, without the need to configure the project.

**Comment by SI3P** [comment]
https://supwsd.net/supwsd/pocket.jsp
