### ISSUE TITLE
API's No Found!

### ISSUE THREAD

**Issue by rodriguesfas** [SI3P/supWSD#2]
Hello, I would love to use the tool, but the API's links are out. :(

**Comment by raganato** [comment]
Hi, currently we have some trouble with the server, but we are planning to move on a more stable one. Probably in a couple of months everything will be up and running again.

**Comment by SI3P** [comment]
We are back online now.

**Comment by rodriguesfas** [comment]
Hello, I'm having an error in the SupWSD function!

for sense in SupWSD.senses(_sent):
AttributeError: type object 'SupWSD' has no attribute 'senses'

**Comment by SI3P** [comment]
Python API:
for sense in SupWSD*()*.senses(text):
...

Java API:
SupWSD swsd = SupWSD.getInstance();
for (SupSense sense : swsd.getSenses(text))
...

Il giorno mer 12 set 2018 alle ore 18:41 RodriguesFAS <
notifications@github.com> ha scritto:

**Comment by NLPting** [comment]
Hello , I like to use it , but if I want to know the meaning of sense , what can I do.
ps. I use python API
ex : Sense: be%2:42:03 , what it is represents?

**Comment by SI3P** [comment]
It is a sense key (as defined by WordNet). To get the gloss you can do this:

**from nltk.corpus import wordnet as wn**
...
for sense in SupWSD().senses(text,False):
       if not sense.miss():
            for result in sense.results:
            **synset=wn.lemma_from_key(result.key).synset()**
            print("Sense key: {} , Gloss: {}".format(result.key, synset.definition()))
