### ISSUE TITLE
503 Server Error

### ISSUE THREAD

**Issue by rodriguesfas** [SI3P/supWSD#7]
I'm trying to use the API, I get the following response: 503 Server Error: Service Unavailable.

**Comment by SI3P** [comment]
I'm sorry for the inconvenience. There's a temporary problem with the OpenShift server that does not depend on us.

**Comment by SI3P** [comment]
The problem seems to have been solved!

**Comment by sidsvash26** [comment]
This issue is coming again.

**Comment by SI3P** [comment]
https://supwsd.net
